apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-cart
  name: ms-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cart
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-cart
    spec:
      containers:
        - image: gcr.io/learning-357114/ms-cart:2.0.0
          name: ms-cart
          resources: {}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
              protocol: TCP
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: ms-cart
  name: ms-cart
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: service-port-grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: service-port-http
      port: 3333
      protocol: TCP
      targetPort: 3333
  selector:
    app: ms-cart
  type: ClusterIP
